In [30]:
import sklearn

In [31]:
# !python -m pip install sklearn

In [32]:
# %load_ext autoreload

# %autoreload 2

In [33]:
import pandas as pd

In [34]:
pd_data = pd.read_csv('C:/Develops/test_machinelearning/files/auto-mpg.csv', header = None)
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
0    398 non-null float64
1    398 non-null int64
2    398 non-null float64
3    398 non-null object
4    398 non-null float64
5    398 non-null float64
6    398 non-null int64
7    398 non-null int64
8    398 non-null object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [71]:
pd_data.shape
pd_data

,0,1,2,3,4,5,6,7,8
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
5,15.0,8,429.0,198.0,4341.0,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220.0,4354.0,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215.0,4312.0,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225.0,4425.0,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190.0,3850.0,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170.0,3563.0,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160.0,3609.0,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761.0,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086.0,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113.0,95.00,2372.0,15.0,70,3,toyota corona mark ii
15,22.0,6,198.0,95.00,2833.0,15.5,70,1,plymouth duster
16,18.0,6,199.0,97.00,2774.0,15.5,70,1,amc hornet
17,21.0,6,200.0,85.00,2587.0,16.0,70,1,ford maverick
18,27.0,4,97.0,88.00,2130.0,14.5,70,3,datsun pl510
19,26.0,4,97.0,46.00,1835.0,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.00,2672.0,17.5,70,2,peugeot 504
21,24.0,4,107.0,90.00,2430.0,14.5,70,2,audi 100 ls
22,25.0,4,104.0,95.00,2375.0,17.5,70,2,saab 99e
23,26.0,4,121.0,113.0,2234.0,12.5,70,2,bmw 2002
24,21.0,6,199.0,90.00,2648.0,15.0,70,1,amc gremlin
25,10.0,8,360.0,215.0,4615.0,14.0,70,1,ford f250
26,10.0,8,307.0,200.0,4376.0,15.0,70,1,chevy c20
27,11.0,8,318.0,210.0,4382.0,13.5,70,1,dodge d200
28,9.0,8,304.0,193.0,4732.0,18.5,70,1,hi 1200d
29,27.0,4,97.0,88.00,2130.0,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27.0,4,112.0,88.00,2640.0,18.6,82,1,chevrolet cavalier wagon
369,34.0,4,112.0,88.00,2395.0,18.0,82,1,chevrolet cavalier 2-door
370,31.0,4,112.0,85.00,2575.0,16.2,82,1,pontiac j2000 se hatchback
371,29.0,4,135.0,84.00,2525.0,16.0,82,1,dodge aries se
372,27.0,4,151.0,90.00,2735.0,18.0,82,1,pontiac phoenix
373,24.0,4,140.0,92.00,2865.0,16.4,82,1,ford fairmont futura
374,23.0,4,151.0,?,3035.0,20.5,82,1,amc concord dl
375,36.0,4,105.0,74.00,1980.0,15.3,82,2,volkswagen rabbit l
376,37.0,4,91.0,68.00,2025.0,18.2,82,3,mazda glc custom l
377,31.0,4,91.0,68.00,1970.0,17.6,82,3,mazda glc custom
378,38.0,4,105.0,63.00,2125.0,14.7,82,1,plymouth horizon miser
379,36.0,4,98.0,70.00,2125.0,17.3,82,1,mercury lynx l
380,36.0,4,120.0,88.00,2160.0,14.5,82,3,nissan stanza xe
381,36.0,4,107.0,75.00,2205.0,14.5,82,3,honda accord
382,34.0,4,108.0,70.00,2245.0,16.9,82,3,toyota corolla
383,38.0,4,91.0,67.00,1965.0,15.0,82,3,honda civic
384,32.0,4,91.0,67.00,1965.0,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67.00,1995.0,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110.0,2945.0,16.4,82,1,buick century limited
387,38.0,6,262.0,85.00,3015.0,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92.00,2585.0,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112.0,2835.0,14.7,82,1,ford granada l
390,32.0,4,144.0,96.00,2665.0,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84.00,2370.0,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90.00,2950.0,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [36]:
pd_data.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name']

In [37]:
x = pd_data[['weight','cylinders']]

In [38]:
y = pd_data[['mpg']]

In [39]:
x.shape, y.shape

((398, 2), (398, 1))

In [40]:
from sklearn.linear_model import LinearRegression

In [41]:
lr = LinearRegression()

In [42]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
# total data
lr.coef_, lr.intercept_

(array([[-0.00641225, -0.70250805]]), array([46.39370235]))

#### `y = -0.00767661x + 46.31736442`

In [44]:
lr.score(x,y)

0.6964013933838316

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((298, 2), (100, 2), (298, 1), (100, 1))

In [47]:
lr_set = LinearRegression()

In [48]:
lr_set.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
lr_set.coef_, lr_set.coef_

(array([[-0.00639571, -0.67447498]]), array([[-0.00639571, -0.67447498]]))

#### `y = -0.00767661x + 46.31736442`

In [50]:
lr_set.score(x,y)

0.6962502585129493

In [51]:
pd_data = pd.read_csv('C:/Develops/test_machinelearning/files/auto-mpg.csv', header = None)
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
0    398 non-null float64
1    398 non-null int64
2    398 non-null float64
3    398 non-null object
4    398 non-null float64
5    398 non-null float64
6    398 non-null int64
7    398 non-null int64
8    398 non-null object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [56]:
lr.score(X_test,Y_test)

0.7727665297233648

In [58]:
lr.score(X_train,Y_train)

0.671749118481318

In [59]:
lr.predict([[3504.0,8]])

array([[18.30511201]])

In [60]:
# 2790.0, 4
lr.predict([[2790.0, 4]])

array([[25.69349111]])

In [61]:
(-0.00767661*2790.0) + (-0.73190678*4) + 46.31736442

21.971995399999997

In [62]:
type(lr)

sklearn.linear_model.base.LinearRegression

In [63]:
import pickle

In [65]:
pickle.dump(lr,open('./saves/autompg_lr.pkl', 'wb'))

In [67]:
y_predict = lr.predict(X_train)
y_predict.shape, Y_train.shape

((298, 1), (298, 1))

In [69]:
y_result = y_predict - Y_train
y_result

           mpg
361  -1.816873
387 -15.154281
164   1.691825
68   -1.094314
140  -0.523313
357  -6.084365
276   4.061430
264   2.122375
42   -2.999064
212  -3.812019
62    0.367679
178   1.622645
390  -5.504978
12    1.657164
115  -0.401169
172   4.329237
266  -0.234730
335  -7.446956
206   0.636247
161   1.190114
213   1.771962
350  -5.319465
151  -0.240831
135   1.011193
242   5.411819
74    0.239434
160   0.125991
126   2.743434
85    1.483411
256  -0.315365
..         ...
22    3.354575
143   2.835494
243   5.344857
261   2.212880
376  -6.401137
147   6.066646
38   -0.215525
389   1.999924
54   -1.759290
201   0.306001
47    2.133648
273   4.262208
39   -1.850649
36    2.005403
9     1.086473
313  -1.588337
133   1.933935
287  -1.086813
364  -9.711995
220  -2.388157
300  -5.056259
13    6.985433
1     2.093197
88    0.855321
232  -3.023468
299  -4.071409
175   2.163141
95   -2.973415
396  -1.248488
89    1.554568

[298 rows x 1 columns]

In [ ]:
lr.score(X_train, Y_train)